### ISSUE TITLE
Unexpected AccessDenied errors

### ISSUE THREAD

**Issue by LachlanStuart** [pywren/pywren-ibm-cloud#242] opened 2019-12-18 09:27 UTC
While running my application in a loop for benchmarking, I got an unexpected Access Denied error in `executor.get_result`:

https://gist.github.com/LachlanStuart/6c7826883f1212b9e09b976950d92794 (exception is at the end)

This happened with an `executor` instance that had already been used for 6 previous successful operations. The first activation with that executor started at `2019-12-17T17:25:49.450713Z` and the last activation finished at `2019-12-17T17:29:28.894917Z`.

The next loop of the benchmark (using a new `executor` instance) had a different, but probably related error: https://gist.github.com/LachlanStuart/0ff767043365806ee606e6dc2ed9497f

After the above 2 errors, everything started working again, however the "Access Denied" happened a total of 6 times across the ~180 rounds of benchmarks, and the "Invalid API Key" happened 5 times, though not always in connection with the "Access Denied".

Using PyWren 1.3.0 with IAM on IBM Cloud

**Comment by gilv** [comment] 2019-12-18 09:35
@JosepSampe this is exactly what i experienced with other flows... and it got resolved by itself after couple of run attempts. I use API key for CF.
I think something in the token manager is wrong to provide tokens to invocations. 
This is something new, we didn't experienced it in the past.

**Comment by JosepSampe** [comment] 2019-12-18 11:05
@LachlanStuart @gilv This issue happens due tokens expiry time. 
In order to alleviate the number of requested tokens to IBM Cloud, a new requested tokens is stored locally so that it can be reused during its lifetime, which is 1 hour. The problem comes when during an experiment the token expires, i.e, you start the experiment when the token is valid, but the experiment takes long and it expires while waiting for the results, producing the exception you see. Then, when you run the experiments again, pywren detects the token is expired and requests a new one, making everything working again.

**Comment by JosepSampe** [comment] 2019-12-18 11:15
@LachlanStuart @gilv This issue happens due tokens expiry time.


In order to alleviate the number of requested tokens to IBM Cloud, a new requested tokens is stored locally so that it can be reused during its lifetime, which is 1 hour. The problem comes when during an experiment the token expires, i.e, you start the experiment when the token is valid, but the experiment takes long and it expires while waiting for the results, producing the exception you see. Then, when you run the experiments again, pywren detects the token is expired and requests a new one, making everything working again.

This is not new, this behavior was introduced in 1.0.20, so maye you are now running longer and more frequent experiments. Also, if instead of using IAM API key for CF and COS API key, you use CloudFoundry API key for CF and hmac credentials for COS, this issue will never happen since with these kind of credentials there are no tokens involved.

**Comment by JosepSampe** [comment] 2019-12-18 14:50
@LachlanStuart just out of curios, not related to the issue, why do you have `annotation_pipeline ` repeated 10s of times here: https://gist.github.com/LachlanStuart/6c7826883f1212b9e09b976950d92794#file-gistfile1-txt-L799 ? Are you appending it to include_modules multiple times? or it might be internal PyWren issue?

**Comment by LachlanStuart** [comment] 2019-12-19 11:04
@JosepSampe I'm not sure why it's there 10 times. I use `%autoreload` in Jupyter Lab, so it's possible that many versions of the same module are still referenced in memory. I'll check whether the number of duplicates grows after code changes next time I'm at my work computer.

It's definitely only in my `include_modules` once:
```
  "pywren": {
    "storage_bucket": "metaspace-lachlan-temp",
    "include_modules": ["annotation_pipeline"],
    "runtime": "ibmfunctions/pywren-metabolomics:3.6.31"
  },
```

**Comment by LachlanStuart** [comment] 2019-12-19 21:17
@JosepSampe It wasn't an `%autoreload` issue as I suspected. Every pywren job added one more `annotation_pipeline` to that same list. The first `executor.map` only logged one `annotation_pipeline`, the second logged two, etc. This happened even without `%autoreload` enabled.

**Comment by JosepSampe** [comment] 2019-12-20 15:41
@LachlanStuart Fixed in #245

**Comment by omerb01** [comment] 2019-12-26 09:00
experienced another "access denied" error with the current master branch (after using a notebook that was run yesterday) :
```
Exception in thread Thread-7754:
Traceback (most recent call last):
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/invoker.py", line 305, in _job_status_checker_worker_os
    callids_done_in_job = set(self.internal_storage.get_job_status(job.executor_id, job.job_id))
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/storage/storage.py", line 142, in get_job_status
    keys = self.storage_handler.list_keys(self.bucket, callset_prefix)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 279, in list_keys
    raise e
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 270, in list_keys
    for page in page_iterator:
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ibm_botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ibm_botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ibm_botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ibm_botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ibm_botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by JosepSampe** [comment] 2019-12-26 12:42
@omerb01 Could you please paste full DEBUG logs (not only exception)

**Comment by omerb01** [comment] 2019-12-27 11:03
@JosepSampe DEBUG logs are too long to put here, I'll send you by mail

**Comment by JosepSampe** [comment] 2019-12-27 16:33
@omerb01 As I stated above, the problem is that the map() takes more than 1 hour to finish, this causes the token to expire while the map() is running, and then the exception.

For this kind of long-term workflows, I would suggest to use HMAC credentials instead of COS API key

**Comment by omerb01** [comment] 2020-01-03 18:19
@JosepSampe do you know if an IAM key is good enough for not experiencing this exception?

**Comment by JosepSampe** [comment] 2020-01-03 23:45
@omerb01 IAM api key also generates a token, so you will experience same exception for this use case.

**Closed** 2020-04-01 08:54 UTC
