### ISSUE TITLE
Docker executor fails when running from multiple users

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#341] opened 2020-08-11 14:47 UTC
when trying to use the docker executor with multiple users for the same remote VM, I get "permissions denied" and I'm stuck in this state. I tried to set `compute_backend: docker` and then run `pywren_ibm_cloud clean` but the script failed.

simple example:
```python
import pywren_ibm_cloud as pywren

def my_map_function(x):
    return x + 7

if __name__ == '__main__':
    pw = pywren.docker_executor(log_level='DEBUG', storage_backend='ibm_cos')
    futures = pw.map(my_map_function, [1, 2])
    print(pw.get_result())
```
output:
```
/Users/omerbelh/.pyenv/versions/3.7.5/bin/python /Users/omerbelh/PycharmProjects/pywren-temp/pywren_vm_example.py
2020-08-11 17:42:38,408 [INFO] pywren_ibm_cloud.config: PyWren v1.7.0
2020-08-11 17:42:38,408 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-08-11 17:42:38,409 [INFO] pywren_ibm_cloud.config: Getting configuration from /Users/omerbelh/.pywren_config
2020-08-11 17:42:38,430 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: docker
2020-08-11 17:42:38,545 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: ibm_cos
2020-08-11 17:42:38,590 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: 4572f7/0
2020-08-11 17:42:38,590 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-08-11 17:42:38,590 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-08-11 17:42:38,590 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-08-11 17:42:38,628 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-08-11 17:42:38,628 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 4572f7/0 - Total available workers: 256
2020-08-11 17:42:38,629 [INFO] pywren_ibm_cloud.compute.backends.docker.docker: PyWren v1.7.0 init for Docker - Host: pywren.sl.cloud9.ibm.com
2020-08-11 17:42:38,629 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 4572f7/0 - Creating function invoker
2020-08-11 17:42:38,645 [INFO] pywren_ibm_cloud.invoker: ExecutorID 4572f7/0 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.7:1.6.0
2020-08-11 17:42:38,645 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in local cache. Retrieving it from storage
2020-08-11 17:42:38,645 [DEBUG] pywren_ibm_cloud.storage.storage: Trying to download runtime metadata from: ibm_cos://omeruseast/pywren.runtimes/1.7.0/docker/pywren.sl.cloud9.ibm.com/pywren_ibmfunctions_action-python-v3.7_1.6.0.meta.json
2020-08-11 17:42:39,643 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in storage
2020-08-11 17:42:39,643 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 4572f7/0 | JobID M000 - Runtime ibmfunctions/action-python-v3.7:1.6.0 with NoneMB is not yet installed
2020-08-11 17:42:39,643 [DEBUG] pywren_ibm_cloud.invoker: Creating runtime: ibmfunctions/action-python-v3.7:1.6.0, memory: NoneMB
2020-08-11 17:42:39,643 [DEBUG] pywren_ibm_cloud.compute.utils: Creating function handler zip in /Users/omerbelh/PycharmProjects/pywren-temp/pywren_docker.zip
2020-08-11 17:42:40,079 [DEBUG] paramiko.transport: starting thread (client mode): 0xff7cf50
2020-08-11 17:42:40,079 [DEBUG] paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.1
2020-08-11 17:42:40,186 [DEBUG] paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
2020-08-11 17:42:40,187 [INFO] paramiko.transport: Connected (version 2.0, client OpenSSH_7.6p1)
2020-08-11 17:42:40,292 [DEBUG] paramiko.transport: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr'] server encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
2020-08-11 17:42:40,293 [DEBUG] paramiko.transport: Kex agreed: curve25519-sha256@libssh.org
2020-08-11 17:42:40,293 [DEBUG] paramiko.transport: HostKey agreed: ssh-ed25519
2020-08-11 17:42:40,293 [DEBUG] paramiko.transport: Cipher agreed: aes128-ctr
2020-08-11 17:42:40,293 [DEBUG] paramiko.transport: MAC agreed: hmac-sha2-256
2020-08-11 17:42:40,293 [DEBUG] paramiko.transport: Compression agreed: none
2020-08-11 17:42:40,459 [DEBUG] paramiko.transport: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2020-08-11 17:42:40,460 [DEBUG] paramiko.transport: Switch to new keys ...
2020-08-11 17:42:40,460 [DEBUG] paramiko.transport: Adding ssh-ed25519 host key for pywren.sl.cloud9.ibm.com: b'bd9e0f6d7df15a45d8349f7b22495497'
2020-08-11 17:42:40,741 [DEBUG] paramiko.transport: userauth is OK
2020-08-11 17:42:40,880 [INFO] paramiko.transport: Authentication (password) successful!
2020-08-11 17:42:40,880 [DEBUG] paramiko.transport: [chan 0] Max packet in: 32768 bytes
2020-08-11 17:42:41,655 [DEBUG] paramiko.transport: Received global request "hostkeys-00@openssh.com"
2020-08-11 17:42:41,655 [DEBUG] paramiko.transport: Rejecting "hostkeys-00@openssh.com" global request from server.
2020-08-11 17:42:41,762 [DEBUG] paramiko.transport: [chan 0] Max packet out: 32768 bytes
2020-08-11 17:42:41,762 [DEBUG] paramiko.transport: Secsh channel 0 opened.
2020-08-11 17:42:41,927 [DEBUG] paramiko.transport: [chan 0] Sesch channel 0 request ok
2020-08-11 17:42:42,037 [INFO] paramiko.transport.sftp: [chan 0] Opened sftp connection (server version 3)
2020-08-11 17:42:42,038 [DEBUG] paramiko.transport.sftp: [chan 0] open(b'/tmp/pywren_docker.zip', 'wb')
2020-08-11 17:42:42,147 [DEBUG] paramiko.transport.sftp: [chan 0] open(b'/tmp/pywren_docker.zip', 'wb') -> 00000000
2020-08-11 17:42:42,490 [DEBUG] paramiko.transport.sftp: [chan 0] close(00000000)
2020-08-11 17:42:42,822 [DEBUG] paramiko.transport.sftp: [chan 0] stat(b'/tmp/pywren_docker.zip')
2020-08-11 17:42:42,929 [INFO] paramiko.transport.sftp: [chan 0] sftp session closed.
2020-08-11 17:42:42,930 [DEBUG] paramiko.transport: [chan 0] EOF sent (0)
2020-08-11 17:42:43,032 [DEBUG] paramiko.transport: EOF in transport thread
2020-08-11 17:42:43,038 [DEBUG] paramiko.transport: starting thread (client mode): 0xff53d50
2020-08-11 17:42:43,039 [DEBUG] paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.1
2020-08-11 17:42:43,151 [DEBUG] paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
2020-08-11 17:42:43,151 [INFO] paramiko.transport: Connected (version 2.0, client OpenSSH_7.6p1)
2020-08-11 17:42:43,265 [DEBUG] paramiko.transport: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr'] server encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
2020-08-11 17:42:43,265 [DEBUG] paramiko.transport: Kex agreed: curve25519-sha256@libssh.org
2020-08-11 17:42:43,266 [DEBUG] paramiko.transport: HostKey agreed: ssh-ed25519
2020-08-11 17:42:43,266 [DEBUG] paramiko.transport: Cipher agreed: aes128-ctr
2020-08-11 17:42:43,266 [DEBUG] paramiko.transport: MAC agreed: hmac-sha2-256
2020-08-11 17:42:43,266 [DEBUG] paramiko.transport: Compression agreed: none
2020-08-11 17:42:43,423 [DEBUG] paramiko.transport: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2020-08-11 17:42:43,424 [DEBUG] paramiko.transport: Switch to new keys ...
2020-08-11 17:42:43,424 [DEBUG] paramiko.transport: Adding ssh-ed25519 host key for pywren.sl.cloud9.ibm.com: b'bd9e0f6d7df15a45d8349f7b22495497'
2020-08-11 17:42:43,748 [DEBUG] paramiko.transport: userauth is OK
2020-08-11 17:42:43,954 [INFO] paramiko.transport: Authentication (password) successful!
2020-08-11 17:42:43,955 [DEBUG] paramiko.transport: [chan 0] Max packet in: 32768 bytes
2020-08-11 17:42:44,671 [DEBUG] paramiko.transport: Received global request "hostkeys-00@openssh.com"
2020-08-11 17:42:44,671 [DEBUG] paramiko.transport: Rejecting "hostkeys-00@openssh.com" global request from server.
2020-08-11 17:42:44,774 [DEBUG] paramiko.transport: [chan 0] Max packet out: 32768 bytes
2020-08-11 17:42:44,774 [DEBUG] paramiko.transport: Secsh channel 0 opened.
2020-08-11 17:42:44,879 [DEBUG] paramiko.transport: [chan 0] Sesch channel 0 request ok
2020-08-11 17:42:44,998 [DEBUG] paramiko.transport: [chan 0] EOF received (0)
2020-08-11 17:42:44,998 [INFO] pywren_ibm_cloud.compute.backends.docker.docker: 
Traceback (most recent call last):
  File "/Users/omerbelh/PycharmProjects/pywren-temp/pywren_vm_example.py", line 11, in <module>
2020-08-11 17:42:44,998 [DEBUG] paramiko.transport: [chan 0] EOF sent (0)
    futures = pw.map(my_map_function, [1, 2])
  File "/Users/omerbelh/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pywren_ibm_cloud/executor.py", line 176, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/omerbelh/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pywren_ibm_cloud/invoker.py", line 125, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/Users/omerbelh/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pywren_ibm_cloud/compute/compute.py", line 63, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/omerbelh/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pywren_ibm_cloud/compute/backends/docker/docker.py", line 203, in create_runtime
    self._ssh_run_remote_command(cmd)
  File "/Users/omerbelh/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pywren_ibm_cloud/compute/backends/docker/docker.py", line 78, in _ssh_run_remote_command
    raise Exception('There was an error pulling the runtime: {}'.format(error))
Exception: There was an error pulling the runtime: rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/storage/backends/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/storage/backends/ibm_cos/__pycache__/ibm_cos.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/storage/backends/ibm_cos/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/storage/__pycache__/utils.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/storage/__pycache__/storage.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/storage/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/invoker.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/config.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/executor.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/utils.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/version.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/future.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/wait/__pycache__/wait_storage.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/wait/__pycache__/wait_rabbitmq.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/wait/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/compute/backends/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/compute/backends/localhost/__pycache__/localhost.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/compute/backends/localhost/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/compute/__pycache__/compute.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/compute/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/job/__pycache__/job.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/job/__pycache__/serialize.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/job/__pycache__/partitioner.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/job/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/tblib/__pycache__/pickling_support.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/tblib/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/tblib/__pycache__/cpython.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/multyvac/__pycache__/module_dependency.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/multyvac/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/glob2/__pycache__/impl.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/glob2/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/glob2/__pycache__/fnmatch.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/cloudpickle/__pycache__/cloudpickle.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/cloudpickle/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/ps_mem/__pycache__/__init__.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/libs/ps_mem/__pycache__/ps_mem.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/function/__pycache__/invoker.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/function/__pycache__/jobrunner.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/function/__pycache__/handler.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/function/__pycache__/utils.cpython-37.pyc': Permission denied
rm: cannot remove '/tmp/pywren-docker/pywren_ibm_cloud/function/__pycache__/__init__.cpython-37.pyc': Permission denied

Process finished with exit code 1
```

**Comment by gilv** [comment] 2020-08-12 04:25
Duplicate of https://github.com/pywren/pywren-ibm-cloud/issues/336

**Comment by gilv** [comment] 2020-08-12 04:41
@omerb01 fixed in https://github.com/pywren/pywren-ibm-cloud/commit/e7c2de623ae1d1cab7d3226aefa6babe6d824bdd
you need to log into your VM, go to /tmp folder and delete all pywren* stuff created there with sudo rm -r..
next time you run it - it will work good

**Closed by gilv** 2020-08-12 04:41 UTC
