### ISSUE TITLE
"runtime not deployed" when operating pywren

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#231] opened 2019-12-01 10:19 UTC
Experienced 2 issues with `pywren-runtime` script:
1. sometimes I get "runtime not deployed" error when I operate PyWren on a runtime (default or customised) and even when I do `pywren-runtime clean`, I still get this error. my simple solution for this is to use another runtime, and then after some time (not immediately), I can return back to the previous runtime and it works as it should (with installation). I am not able to reproduce the error right now.
2. `build` parameter doesn't work, for example when I do:
```
pywren-runtime build omerb01/pywren-omer-runtime:3.6.16 -f runtime/Dockerfile
```
I get:
```
DEBUG:pywren_ibm_cloud.config:Loading configuration
DEBUG:pywren_ibm_cloud.config:Loading Compute backend module: ibm_cf
DEBUG:pywren_ibm_cloud.config:Loading Storage backend module: ibm_cos
DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Creating IBM Cloud Functions client
DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Set IBM CF Namespace to pywren_dev_us_east
DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Set IBM CF Endpoint to https://us-east.functions.cloud.ibm.com
DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:IBM CF client created successfully
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Building a new docker image from Dockerfile
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Docker image name: omerb01/pywren-omer-runtime:3.6.16
sh: docker: command not found
```

**Comment by JosepSampe** [comment] 2019-12-01 18:07
1. Regarding the first issue, when you see "runtime not deployed"? when you run functions or when you execute pywren-runtime script?

2. Regarding the second issue, internally pywren executes the "docker" console command, so in this case it says that it is unable to find the command. Can you execute the **docker** command from the console?

**Comment by omerb01** [comment] 2019-12-02 07:09
@JosepSampe 
>Regarding the first issue, when you see "runtime not deployed"? when you run functions or when you execute pywren-runtime script?

when I run functions
>Regarding the second issue, internally pywren executes the "docker" console command, so in this case it says that it is unable to find the command. Can you execute the docker command from the console?

I cant, maybe we need to add docker to pywren's installation script?

**Comment by JosepSampe** [comment] 2019-12-02 15:45
@omerb01 Re. docker command, it is a system service, not a python package, so I think it is not possible to put it in the setup.py. In the runtime instructions we already stated that it is needed to install Docker CE version if you want to create your own runtimes ;)

Re. first issue, 'runtime not deployed" exception is raised [here](https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/libs/ibm_cloudfunctions/client.py#L228), in the IBM CF client, and due to 404 response. I will try to reproduce the exception, but can you check if the function exists in your namespace immediately after you get the exception?

**Comment by omerb01** [comment] 2019-12-03 09:35
@JosepSampe do you mean inside CF interface?

**Comment by JosepSampe** [comment] 2019-12-03 09:50
@omerb01 yes

**Comment by omerb01** [comment] 2019-12-12 12:07
@JosepSampe got `Exception: Runtime: omerb01_pywren-omer-runtime_3.6.16_2048MB not deployed` again.
I don't see any actions named like this in my namespace in CF dashboard

**Comment by JosepSampe** [comment] 2019-12-12 13:09
I've never experienced this... Which steps are you following that you finally observe this? 

I think the only way to get this exception is if you manually delete the action/pywren package from your namespace without using pywren-runtime script

**Comment by omerb01** [comment] 2019-12-12 13:56
@JosepSampe maybe when someone else uses `pywren-runtime clean` (I assume that @gilv used it) in my namespace, it deletes the action but doesn't delete stored data related inside COS (because it is stored in my bucket). what do you think?

**Comment by JosepSampe** [comment] 2019-12-12 14:31
@omerb01 Yep, it looks like what you describe if you use same CF namespace

**Comment by omerb01** [comment] 2019-12-12 14:54
@JosepSampe I think that in practice, each namespace could be shared by multiple people, is it possible to fix?

**Comment by JosepSampe** [comment] 2019-12-12 15:07
@omerb01 Now we know the source of the issue yes

**Comment by JosepSampe** [comment] 2020-01-04 07:20
I was thinking about it, and the easiest way to proceed is to differentiate between packages in the CF namespace so that each user has its own pywren package.  To do so we can add a suffix that identifies the user who created that package.

He have multiple options, for example, use a subset of the api_key of each user, so that the pywren package in the CF namespace will looks like this (for 3 different users):
```
pywren_v1.3.1-SNAPSHOT-6a624f7f
pywren_v1.3.1-SNAPSHOT-555sd48s
pywren_v1.3.1-SNAPSHOT-3s64ssdf
```
or we can add an extra config variable `username` in `ibm_cf` section, so that the pywren package will looks like this:
```
pywren_v1.3.1-SNAPSHOT-josep
pywren_v1.3.1-SNAPSHOT-gilv
pywren_v1.3.1-SNAPSHOT-omer
```
@omerb01 @gilv What do you think?

**Comment by omerb01** [comment] 2020-01-05 10:35
@JosepSampe I think it's a great solution, I support in the API key solution cause it simplifies the config file - but we do need an option for the `pywren-runtime` script to clean all packages available in the namespace as well.

**Comment by gilv** [comment] 2020-01-14 06:18
@JosepSampe @omerb01 can we close this one?

**Comment by omerb01** [comment] 2020-01-15 08:22
@JosepSampe Thanks, I saw that you added suffixes for PyWren's package in CF. do you plan to add an option for `pywren-runtime` script to delete all available packages in the namespace?

**Comment by JosepSampe** [comment] 2020-01-15 08:48
@omerb01 I can add something like `pywren-runtime clean all`
However, it won't clean runtimes metadata from the other users COS bucket. So if you delete all available packages in the namespace,  the other users will get "runtime not deployed" when operating pywren again.

**Comment by omerb01** [comment] 2020-01-15 09:04
@JosepSampe I see, so maybe it's better to leave it as it is, thanks :)

**Closed** 2020-01-15 09:55 UTC
