### ISSUE TITLE
Errors running testpywren.py

### ISSUE THREAD

**Issue by spitfiredd** [pywren/pywren-ibm-cloud#118] opened 2019-04-10 21:25 UTC
I am getting errors when run `python testpywren.py`.

I am able run `python testpywren.py init` and i get the following outout

```
Uploading test files...
Upload file: __pywren.test/test0 - SUCCESS
Upload file: __pywren.test/test1 - SUCCESS
Upload file: __pywren.test/test2 - SUCCESS
Upload file: __pywren.test/test3 - SUCCESS
Upload file: __pywren.test/test4 - SUCCESS
Upload file: __pywren.test/result - SUCCESS
ALL DONE
```

I can verify that these files have been created from the dashboard.

However, when I run `python testpywren.py`. I get the following,

```
IBM Cloud Functions init for Namespace: myemail@gmail.com_dev
IBM Cloud Functions init for Host: https://us-south.functions.cloud.ibm.com
IBM Cloud Functions init for Runtime: ibmfunctions/action-python-v3.7 - 256MB (Installing...)
The filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
EThe filename, directory name, or volume label syntax is incorrect.
```

Pretty much copied an pasted the config variables from, https://cloud.ibm.com/openwhisk/learn/api-key

![image](https://user-images.githubusercontent.com/2820827/55914194-84b1da80-5bb4-11e9-88b2-11d82ffda810.png)

I made sure that I prefixed https:// to endpoint, 
`endpoint    : https://us-south.functions.cloud.ibm.com`

I was also able to run the "hello world" example from https://console.bluemix.net/docs/openwhisk/openwhisk_actions.html#creating-python-actions

I am not sure what I am doing wrong other than I have entered the wrong config variables, which looks like,

```
pywren: 
    storage_bucket: spif-pywren-bucket

ibm_cf:
    # Obtain all values from https://cloud.ibm.com/openwhisk/learn/api-key
    endpoint    : https://us-south.functions.cloud.ibm.com
    namespace   : myemail@gmail.com_dev
    api_key     : copied_from_above_link
   
ibm_cos:
    # Region endpoint example: https://s3.us-east.cloud-object-storage.appdomain.cloud
    endpoint   : https://s3.us-east.cloud-object-storage.appdomain.cloud
    # this is preferable authentication method for IBM COS
    api_key    :  copied_from_cos_dashboard
    # alternatively you may use HMAC authentication method
    # access_key : <ACCESS_KEY>
    # secret_key : <SECRET_KEY>

```

**Comment by JosepSampe** [comment] 2019-04-10 21:38
Hi @spitfiredd, config file seems to be ok.  Which operating system are you using?

**Comment by spitfiredd** [comment] 2019-04-10 21:53
Windows 10

**Comment by JosepSampe** [comment] 2019-04-10 22:14
I think the problem is how you set the config file location into path:
https://stackoverflow.com/questions/24782826/the-filename-directory-name-or-volume-label-syntax-is-incorrect-inside-batch

**Comment by spitfiredd** [comment] 2019-04-10 22:19
I have it stored in a `.env` file,

`PYWREN_CONFIG_FILE="D:\python\pywren-ibm\.pywren_config"`

```
(.venv) D:\python\pywren-ibm>echo %PYWREN_CONFIG_FILE%
D:\python\pywren-ibm\.pywren_config
```

**Comment by JosepSampe** [comment] 2019-04-10 22:34
Which PyWren version do you have installed?

**Comment by spitfiredd** [comment] 2019-04-10 23:00
I have both pywren and pywren-ibm-cloud installed in separate isolated virtual envs.

**Comment by JosepSampe** [comment] 2019-04-10 23:03
I mean, pywren-ibm-cloud version. 
Because I think  `pywren-ibm-cloud==1.0.8` may solve the issue

**Comment by spitfiredd** [comment] 2019-04-10 23:04
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pywren_ibm_cloud

In [2]: pywren_ibm_cloud.__version__
Out[2]: '1.0.8'
```

**Comment by JosepSampe** [comment] 2019-04-10 23:07
thanks, will check what may happen

**Comment by spitfiredd** [comment] 2019-04-10 23:16
Oh! When I run this in a regular python terminal I get a traceback (an ipython shell wasn't printing the whole traceback)

I also copied all my info into a dict in a `config.py`.

```
>>> pw = pywren.ibm_cf_executor(config=config)
IBM Cloud Functions init for Namespace: spitfiredd@gmail.com_dev
IBM Cloud Functions init for Host: https://us-south.functions.cloud.ibm.com
IBM Cloud Functions init for Runtime: ibmfunctions/action-python-v3.7 - 256MB (Installing...)
The filename, directory name, or volume label syntax is incorrect.
Traceback (most recent call last):
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\storage\backends\cos.py", line 115, in get_object
    r = self.cos_client.get_object(Bucket=bucket_name, Key=key, **extra_get_args)
  File "D:\python\pywren-ibm\.venv\lib\site-packages\ibm_botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "D:\python\pywren-ibm\.venv\lib\site-packages\ibm_botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ibm_botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\storage\storage.py", line 137, in get_runtime_info
    json_str = self.backend_handler.get_object(self.storage_bucket, key)
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\storage\backends\cos.py", line 123, in get_object
    raise StorageNoSuchKeyError(key)
pywren_ibm_cloud.storage.exceptions.StorageNoSuchKeyError: No such key runtimes\1.0.8\ibmfunctions/action-python-v3.7_256.meta.json found in storage.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\runtime\metadata.py", line 33, in get_runtime_preinstalls
    runtime_meta = internal_storage.get_runtime_info('{}_{}'.format(runtime, memory))
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\storage\storage.py", line 141, in get_runtime_info
    raise Exception('The runtime {} is not installed.'.format(runtime_name))
Exception: The runtime ibmfunctions/action-python-v3.7_256 is not installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\wren.py", line 100, in __init__
    self.executor = Executor(invoker, self.config, self.internal_storage)
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\executor.py", line 52, in __init__
    self.config)
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\runtime\metadata.py", line 44, in get_runtime_preinstalls
    clone_runtime(runtime, memory=memory, config=config)
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\runtime\deploy_utils.py", line 134, in clone_runtime
    _create_zip_action()
  File "D:\python\pywren-ibm\.venv\lib\site-packages\pywren_ibm_cloud\runtime\deploy_utils.py", line 45, in _create_zip_action
    raise Exception('Unable to create the {} action package'.format(ZIP_LOCATION))
Exception: Unable to create the D:\python\pywren-ibm/ibmcf_pywren.zip action package
```

**Comment by JosepSampe** [comment] 2019-04-10 23:29
Thanks, I think I already know how to fix it.
Just for replicating, how did you install your virtenv on Windows?

**Comment by spitfiredd** [comment] 2019-04-10 23:34
pipenv

**Comment by JosepSampe** [comment] 2019-04-11 18:32
@spitfiredd Already fixed in #120, Wait till @gilv merge it.

**Comment by gilv** [comment] 2019-04-11 19:53
@spitfiredd @JosepSampe merged

**Comment by spitfiredd** [comment] 2019-04-11 22:55
This fixes the issue.

**Closed** 2019-04-12 03:15 UTC
